# ===================================
#  Relation Behavior Config
# ===================================

client:
    label: Client
    view:
        form: $/waka/crsm/models/client/fields_for_contacts_show.yaml
        toolbarButtons: create|update|link|unlink
    manage:
        form: $/waka/crsm/models/client/fields_for_contacts.yaml
        list: $/waka/crsm/models/client/columns.yaml
        showSearch: true



