# ===================================
#  Form Behavior Config
# ===================================

fields:
    information:
        labelFrom: completeName
        headingLevel: h2
        class: br-a
        type: title

    listContact:
        label: waka.crsm::lang.contact.data_contact
        headingLevel: h4
        type: info_list
        icon: icon-id-card
        fields:
            name:
                label:  waka.crsm::lang.contact.name
            surname:
                label: waka.crsm::lang.contact.surname
            email:
                label: waka.crsm::lang.contact.email
    listCLient:
        label: waka.crsm::lang.client.client
        headingLevel: h4
        type: info_list
        icon: icon-building
        fields:
            client.name:
                label: waka.crsm::lang.client.name
            client.country.name:
                label: waka.crsm::lang.client.country
    buttonClient:
        label:  waka.crsm::lang.contact.goto_client_form
        type: button_url
        url: waka/crsm/clients/update/
        modelid: client.id
        icon: icon-external-link-square
        class: btn-xs

    montages:
        type: model_list
        headingLevel: h4
        icon: icon-object-group
        label: waka.crsm::lang.contact.photo_client
        dataHandler: onCallPopupModelCloudis
        modelId: id
        



