# ===================================
#  Relation Behavior Config
# ===================================




contacts:
    label: waka.crsm::lang.contact.name
    manage:
        form: $/waka/crsm/models/contact/fields.yaml
        list: $/waka/crsm/models/contact/fields.yaml
    view:
        
        list: $/waka/crsm/models/contact/columns.yaml
        toolbarButtons: create|delete
        defaultSort:
            column: sort_order
            direction: asc



